apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  # namespace: backend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asedhain/homely-app:v0.1.0
          imagePullPolicy: Always
          #imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-configs-backend
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      # imagePullSecrets:
      #   - name: regcred1
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  # namespace: backend-namespace
  labels:
    name: backend-service
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
