apiVersion: v1
data:
  ALLOWED_ORIGINS: '["http://localhost:5001"]'
  REACT_APP_HOST: "localhost"
  REACT_APP_PORT: "8080"
  REACT_APP_PROTOCOL: http
  REACT_APP_BACKEND_API_URL: http://localhost:5000

  REACT_APP_TYPESENSE_API_KEY: xyz
  REACT_APP_TYPESENSE_CONNECTION_TIMEOUT: "300"

  REACT_APP_GOOGLE_API_KEY: AIzaSyC2aJ3XbxATCWNMRJH_LieUwNWY2rWwkb0
  

kind: ConfigMap
metadata:
  name: app-configs-frontend
  # namespace: homely-namespace
